default_icon: "➡"
event_organizers_icon:
  "^Upstream$": "🏢"
  "colleague2@chmouel.com": "😈"
  "boss@chmouel.com": "🤠"
title_match_icon:
  "^.*kid pickup.*": "👨‍👩‍👧‍👦"
  "^[Project to the Moon].*": "🌕️"
max_results: 10
skip_non_accepted: true
my_emails:
  - email@email.com
# The time to query Gnome Online Accounts not to refresh calendars
refresh_interval: 300
restrict_to_calendar:
  - Work
title_max_char: 20
calendar_day_prefix_url: "https://calendar.google.com/calendar/r/day/"
